# The variables for ICP installation
yum_repository_url: http://storage4.csplab.local/storage/cdimages/rhel7-u5-server-x86_64/
docker_install_file: /downloads/icp-docker-18.03.1_x86_64.bin
icp_images_folder: /downloads
icp_install_file: /downloads/ibm-cloud-private-x86_64-3.1.2.tar.gz
icp_install_folder: /opt/ibm-cloud-private-3.1.2
icp_install_image: ibmcom/icp-inception-amd64:3.1.2-ee
config_yaml: conf/redhat/config.312.yaml
node_hosts: conf/redhat/hosts

# The variables for NFS
nfs_exports: ["/storage/persistentvolumes *(rw,no_root_squash)", "/storage/registry *(rw,no_root_squash)", "/storage/audit *(rw,no_root_squash)"]


# The variables for LDAP
cluster_server: https://172.16.52.217:8443
admin_name: admin
admin_password: admin

LDAP_ID: dbamc-ldap
LDAP_URL: ldap://172.16.52.212:389
LDAP_BASEDN: o=ibm,c=us
LDAP_BINDDN: cn=root
# password of the BIND DN. It should be base64 encoded
LDAP_BINDPASSWORD: UHJ1bmUyMDE5
LDAP_TYPE: Custom
LDAP_USERFILTER: "(&(cn=%v)(objectclass=person))"
LDAP_USERIDMAP: "*:uid"
LDAP_GROUPFILTER: "(&(cn=%v)(|(objectclass=groupOfNames)(objectclass=groupOfUniqueNames)(objectclass=groupOfURLs)))"
LDAP_GROUPIDMAP: "*:cn"
LDAP_GROUPMEMBERIDMAP: groupOfNames:member