# Playbook : Uninstall DBAMC for ICP

- hosts: boot
  remote_user: root
  tasks:
    - name: Install ICP CLI
      include: tasks/install-icp-cli.yaml
      tags:
      - install_cli

    - name: Purge BAI
      shell: |
        helm delete {{ package_name }} --purge --tls
      environment:
        HELM_HOME: /root/.helm
      ignore_errors: yes        
      tags:
      - purge_bai

    - name: Delete PV and PVC in ICP
      block:
      - name: Prepare pv yaml from template
        template:
          src: templates/pv.yaml.j2
          dest: /root/pv.yaml
      - name: Delete PV
        shell: |
          kubectl delete -f /root/pv.yaml
        ignore_errors: yes
      tags:
      - delete_pv
    
- hosts: nfs
  remote_user: root
  tasks:
    - name: Remove NFS Folders {{ pv_root_folder }}
      file:
        path: "{{ pv_root_folder }}"
        state: absent
      tags:
      - delete_nfs